### ISSUE TITLE
Valid replay crashes console application

### ISSUE THREAD

**Issue by stevegee58** [Shiqan/FortniteReplayDecompressor#38]
I've attached one of my replay files causes a crash in my console app in case you're interested.  Fortnite replays it without a problem.
[UnsavedReplay-2022.01.22-20.04.48.zip](https://github.com/Shiqan/FortniteReplayDecompressor/files/7944592/UnsavedReplay-2022.01.22-20.04.48.zip)

**Comment by Shiqan** [comment]
Hi @stevegee58 , I seems to work fine for me on both the master branch and the latest feature/di branch. What kind of error do you get?

**Comment by stevegee58** [comment]
Interesting.  I had another file that crashed but after rebuilding the whole solution it worked.  In this case rebuilding didn't help.
I'm using Visual Studio Community 2019.

Here's the crash output:
`fail: ConsoleReader.Program[0]
      failed ReceivedRawBunch, index: 448
      System.NullReferenceException: Object reference not set to an instance of an object.
         at FortniteReplayReader.Models.NetFieldExports.HealthSet.set_<HealthBaseValue>k__BackingField(INetFieldExportGroup , Object )
         at Unreal.Core.NetFieldParser.CreateType(String group) in C:\Users\steve.guercio\Desktop\stuff\FortniteReplayAnalyzer\FortniteReplayDecompressor\src\Unreal.Core\NetFieldParser.cs:line 577
         at Unreal.Core.ReplayReader`1.ReceiveProperties(FBitArchive archive, NetFieldExportGroup group, UInt32 channelIndex, INetFieldExportGroup& exportGroup, Boolean enablePropertyChecksum, Boolean netDeltaUpdate) in C:\Users\steve.guercio\Desktop\stuff\FortniteReplayAnalyzer\FortniteReplayDecompressor\src\Unreal.Core\ReplayReader.cs:line 1619
         at Unreal.Core.ReplayReader`1.ReceivedReplicatorBunch(DataBunch bunch, FBitArchive archive, Nullable`1 repObject, Boolean bHasRepLayout) in C:\Users\steve.guercio\Desktop\stuff\FortniteReplayAnalyzer\FortniteReplayDecompressor\src\Unreal.Core\ReplayReader.cs:line 1278
         at Unreal.Core.ReplayReader`1.ProcessBunch(DataBunch bunch) in C:\Users\steve.guercio\Desktop\stuff\FortniteReplayAnalyzer\FortniteReplayDecompressor\src\Unreal.Core\ReplayReader.cs:line 1241
         at Unreal.Core.ReplayReader`1.ReceivedSequencedBunch(DataBunch bunch) in C:\Users\steve.guercio\Desktop\stuff\FortniteReplayAnalyzer\FortniteReplayDecompressor\src\Unreal.Core\ReplayReader.cs:line 1104
         at Unreal.Core.ReplayReader`1.ReceivedNextBunch(DataBunch bunch) in C:\Users\steve.guercio\Desktop\stuff\FortniteReplayAnalyzer\FortniteReplayDecompressor\src\Unreal.Core\ReplayReader.cs:line 1096
         at Unreal.Core.ReplayReader`1.ReceivedRawBunch(DataBunch bunch) in C:\Users\steve.guercio\Desktop\stuff\FortniteReplayAnalyzer\FortniteReplayDecompressor\src\Unreal.Core\ReplayReader.cs:line 954
         at Unreal.Core.ReplayReader`1.ReceivedPacket(FBitArchive bitReader) in C:\Users\steve.guercio\Desktop\stuff\FortniteReplayAnalyzer\FortniteReplayDecompressor\src\Unreal.Core\ReplayReader.cs:line 2098
f`

**Comment by Shiqan** [comment]
The error message helped me find the issue ;) 
Basically, these lines should be done for both 'normal' export groups and handle export groups: https://github.com/Shiqan/FortniteReplayDecompressor/blob/master/src/Unreal.Core/NetFieldParser.cs#L198
I've committed a fix to a feature branch. 
Let me know if you want it on master instead :)

**Comment by stevegee58** [comment]
Thanks a lot!  Do I need to install .NET 6.0?  I only have 5.0 with VS 2019

**Comment by stevegee58** [comment]
I installed VS 2022 and got your feature branch to build but the PlayerData field in the replay appears to be empty.
Maybe committing the fix to master would be best for now.

**Comment by Shiqan** [comment]
Should release in a bit :)

**Comment by stevegee58** [comment]
Yay it worked!  Thanks!
