### ISSUE TITLE
New Season Issues with Replay: System.IndexOutOfRangeException

### ISSUE THREAD

**Issue by dabbers** [Shiqan/FortniteReplayDecompressor#58]
Seeing some errors in the new release, unsure how to proceed here. Any help would be appreciated. This occurs directly on the first 
`var replay = reader.ReadReplay(replayFile);`

Replay file: https://static.gamergalaxy.net/replays/fortnite/44c3fcf2-eecf-49fa-b879-b3ece1b69919.replay

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Unreal.Core.ReplayReader`1.ReadNetFieldExports(FArchive archive) in /Users/dab/Downloads/FortniteReplayDecompressor-master 2/src/Unreal.Core/ReplayReader.cs:line 772
   at Unreal.Core.ReplayReader`1.ReadExportData(FArchive archive) in /Users/dab/Downloads/FortniteReplayDecompressor-master 2/src/Unreal.Core/ReplayReader.cs:line 714
   at Unreal.Core.ReplayReader`1.ReadDemoFrameIntoPlaybackPackets(FArchive archive) in /Users/dab/Downloads/FortniteReplayDecompressor-master 2/src/Unreal.Core/ReplayReader.cs:line 797
   at Unreal.Core.ReplayReader`1.ReadReplayData(FArchive archive, Int32 fallbackChunkSize) in /Users/dab/Downloads/FortniteReplayDecompressor-master 2/src/Unreal.Core/ReplayReader.cs:line 385
```

Also seeing:
`      Found unexpected EngineNetworkVersionHistory: 36`

**Comment by Shiqan** [comment]
Thanks for creating an issue.
Had a quick look, and the array of  `NetFieldExports` in the `NetFieldExportGroup` should be able to grow dynamically now.
It used to give you the number of exports in that group, it still does but apparently you can receive a new number for that group size 😄 
I will try to fix this tomorrow.

**Comment by szymczerko** [comment]
hey @Shiqan - is the issue fixed? :D

**Comment by szymczerko** [comment]
I tried to fix this issue. However - with my code the issue is still present.. :/

```
public virtual void ReadNetFieldExports(FArchive archive)
    {
        var numLayoutCmdExports = archive.ReadIntPacked();
        for (var i = 0; i < numLayoutCmdExports; i++)
        {
            var pathNameIndex = archive.ReadIntPacked();
            var isExported = archive.ReadIntPacked() == 1;
            NetFieldExportGroup? group;

            if (isExported)
            {
                var pathName = archive.ReadFString();
                var numExports = archive.ReadIntPacked();

                if (numExports <= 0)
                {
                    _logger?.LogWarning($"Invalid number of exports ({numExports}) for path '{pathName}' at index {pathNameIndex}. Skipping...");
                    continue;
                }

                if (!_netGuidCache.NetFieldExportGroupMap.TryGetValue(pathName, out group))
                {
                    group = new NetFieldExportGroup
                    {
                        PathName = pathName,
                        PathNameIndex = pathNameIndex,
                        NetFieldExportsLength = numExports,
                        NetFieldExports = new NetFieldExport[numExports] // This will now be safe
                    };
                    _netGuidCache.AddToExportGroupMap(pathName, group);
                }
            }
            else
            {
                group = _netGuidCache.GetNetFieldExportGroupFromIndex(pathNameIndex);
            }

            var netField = ReadNetFieldExport(archive);
            if (group != null && netField != null)
            {
                if (netField.Handle >= 0 && netField.Handle < group.NetFieldExportsLength)
                {
                    group.NetFieldExports[netField.Handle] = netField;
                }
                else
                {
                    _logger?.LogWarning($"NetField handle {netField.Handle} is out of bounds for NetFieldExports array of length {group.NetFieldExportsLength}.");
                }
            }
            else
            {
                _logger?.LogInformation("ReceiveNetFieldExports: Unable to find NetFieldExportGroup for export.");
            }
        }
    }
```
